[env:esp32dev]
platform = espressif32
framework = espidf
board = esp32dev
build_flags = -std=gnu++20
lib_deps =
    https://github.com/ESPressio-Development-Platform/EDP-System.git
    https://github.com/ESPressio-Development-Platform/EDP-Persistence.git
