[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = esp32dev
build_unflags = -std=gnu++11
build_flags = -std=gnu++20
lib_deps =
    https://github.com/ESPressio-Development-Platform/EDP-System.git
    https://github.com/ESPressio-Development-Platform/EDP-Persistence.git
